### ISSUE TITLE
Update for macOS 10.12.4 or newer

### ISSUE THREAD

**Issue by kiryph** [egeerardyn/alfred-texdoc#3]
When installing `alfred-texdoc` on macOS 10.12.4 and alfred 3.5.1, alfred complains with 

> This workflow contains a python library incompatible with macOS Sierra 10.12.4+

 and points the user to following webpage: https://www.alfredapp.com/help/troubleshooting/incompatible-python-workflow-library/

Would you mind updating your workflow on http://www.packal.org/workflow/texdoc?

**Comment by egeerardyn** [comment]
Thank you for reporting this.
